- name: Check Top CPU process
  shell: "ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -n 6"
  register: cpu_report
  
- name: Kill top CPU process
  shell: "kill -9 $(ps -eo pid,%cpu --sort=-%cpu | awk 'NR==2{print $1}')"
  when: cpu_report.stdout_lines[1] is defined

- name: Log killed PID
  debug:
    msg: "Killed top CPU hog process: {{ cpu_kill.stdout }}"
